import dotenv from 'dotenv';
import mongoose from 'mongoose';
import crypto from 'crypto';
import ConflictRawEvent from '../services/conflict-intel/models/ConflictRawEvent.js';
import ConflictEvent from '../services/conflict-intel/models/ConflictEvent.js';
import buildZones from '../services/conflict-intel/processors/buildZones.js';
import { computeExpiresAt } from '../services/conflict-intel/utils/timeDecay.js';

dotenv.config({ path: new URL('../.env', import.meta.url) });

function hoursAgo(hours) {
  return new Date(Date.now() - hours * 60 * 60 * 1000);
}

const PLACEHOLDER_EVENTS = [
  {
    sourceEventId: 'ph-ukr-kyiv-bridge-strike',
    primarySource: 'placeholder',
    category: 'airstrike',
    subcategory: 'missile_strike',
    severity: 5,
    confidence: 0.92,
    verificationCount: 3,
    title: 'Kyiv logistics bridge strike disrupts evacuation corridor staging',
    description: 'Placeholder operational report: repeated missile impacts near a logistics bridge east of Kyiv have disrupted convoy timing, damaged traffic-control equipment, and forced rerouting of outbound civilian transport.',
    tags: ['placeholder', 'ukraine', 'bridge_damage', 'evacuation_corridor'],
    location: { lng: 30.6121, lat: 50.4508 },
    locationName: 'Kyiv eastern logistics approach',
    country: 'Ukraine',
    reportedAt: hoursAgo(2),
    raw: {
      source: 'placeholder',
      eventType: 'airstrike',
      eventSubType: 'missile_strike',
      locationName: 'Kyiv eastern logistics approach',
    },
  },
  {
    sourceEventId: 'ph-ukr-kharkiv-shelling',
    primarySource: 'placeholder',
    category: 'armed_conflict',
    subcategory: 'shelling',
    severity: 4,
    confidence: 0.87,
    verificationCount: 2,
    title: 'Kharkiv perimeter shelling threatens pickup routing windows',
    description: 'Placeholder operational report: intermittent shelling around the northern Kharkiv perimeter is compressing safe movement windows for pickup buses and causing repeated dispatch holds.',
    tags: ['placeholder', 'ukraine', 'shelling', 'pickup-delay'],
    location: { lng: 36.2304, lat: 49.9935 },
    locationName: 'Kharkiv northern perimeter',
    country: 'Ukraine',
    reportedAt: hoursAgo(4),
    raw: {
      source: 'placeholder',
      eventType: 'armed_conflict',
      eventSubType: 'shelling',
      locationName: 'Kharkiv northern perimeter',
    },
  },
  {
    sourceEventId: 'ph-ukr-odesa-port-fire',
    primarySource: 'placeholder',
    category: 'fire',
    subcategory: 'port_infrastructure_fire',
    severity: 3,
    confidence: 0.81,
    verificationCount: 2,
    title: 'Odesa port-area fire reduces coastal evacuation throughput',
    description: 'Placeholder operational report: a sustained industrial fire near the Odesa port apron is constraining staging space, reducing visibility, and slowing loading operations for maritime-side evacuation support.',
    tags: ['placeholder', 'ukraine', 'fire', 'port_disruption'],
    location: { lng: 30.7233, lat: 46.4825 },
    locationName: 'Odesa port district',
    country: 'Ukraine',
    reportedAt: hoursAgo(6),
    raw: {
      source: 'placeholder',
      eventType: 'fire',
      eventSubType: 'port_infrastructure_fire',
      locationName: 'Odesa port district',
    },
  },
  {
    sourceEventId: 'ph-lbn-beirut-unrest',
    primarySource: 'placeholder',
    category: 'unrest',
    subcategory: 'urban_protest',
    severity: 2,
    confidence: 0.76,
    verificationCount: 2,
    title: 'Beirut urban unrest complicates assembly-point access',
    description: 'Placeholder operational report: protest activity and street closures in central Beirut are slowing passenger movement to organized assembly points and complicating police-assisted traffic management.',
    tags: ['placeholder', 'lebanon', 'unrest', 'street_closure'],
    location: { lng: 35.5018, lat: 33.8938 },
    locationName: 'Central Beirut',
    country: 'Lebanon',
    reportedAt: hoursAgo(3),
    raw: {
      source: 'placeholder',
      eventType: 'unrest',
      eventSubType: 'urban_protest',
      locationName: 'Central Beirut',
    },
  },
  {
    sourceEventId: 'ph-lbn-tyre-road-blockade',
    primarySource: 'placeholder',
    category: 'blockade',
    subcategory: 'road_checkpoint',
    severity: 4,
    confidence: 0.84,
    verificationCount: 3,
    title: 'Southern Lebanon checkpoint blockade limits Tyre corridor movement',
    description: 'Placeholder operational report: multiple armed checkpoints south of Tyre are restricting bus passage, forcing lengthy inspection delays, and narrowing viable outbound evacuation corridors.',
    tags: ['placeholder', 'lebanon', 'blockade', 'checkpoint'],
    location: { lng: 35.1967, lat: 33.2704 },
    locationName: 'Tyre southern corridor',
    country: 'Lebanon',
    reportedAt: hoursAgo(5),
    raw: {
      source: 'placeholder',
      eventType: 'blockade',
      eventSubType: 'road_checkpoint',
      locationName: 'Tyre southern corridor',
    },
  },
  {
    sourceEventId: 'ph-syr-aleppo-strike-cluster',
    primarySource: 'placeholder',
    category: 'airstrike',
    subcategory: 'urban_strike_cluster',
    severity: 5,
    confidence: 0.91,
    verificationCount: 3,
    title: 'Aleppo strike cluster creates no-go pocket around shelter corridor',
    description: 'Placeholder operational report: a cluster of high-intensity strikes near eastern Aleppo has created an unstable no-go area affecting shelter access roads, fuel staging, and ambulance routing.',
    tags: ['placeholder', 'syria', 'airstrike', 'no_go_zone'],
    location: { lng: 37.1586, lat: 36.2021 },
    locationName: 'Eastern Aleppo',
    country: 'Syria',
    reportedAt: hoursAgo(1.5),
    raw: {
      source: 'placeholder',
      eventType: 'airstrike',
      eventSubType: 'urban_strike_cluster',
      locationName: 'Eastern Aleppo',
    },
  },
  {
    sourceEventId: 'ph-syr-homs-checkpoint-belt',
    primarySource: 'placeholder',
    category: 'blockade',
    subcategory: 'checkpoint_belt',
    severity: 4,
    confidence: 0.83,
    verificationCount: 2,
    title: 'Homs checkpoint belt slows north-south civilian transfer',
    description: 'Placeholder operational report: a dense checkpoint belt west of Homs is causing repeated stop-and-search delays, reducing transfer cadence for scheduled civilian pickup movements.',
    tags: ['placeholder', 'syria', 'blockade', 'transfer_delay'],
    location: { lng: 36.7234, lat: 34.7324 },
    locationName: 'Homs western transfer belt',
    country: 'Syria',
    reportedAt: hoursAgo(7),
    raw: {
      source: 'placeholder',
      eventType: 'blockade',
      eventSubType: 'checkpoint_belt',
      locationName: 'Homs western transfer belt',
    },
  },
  {
    sourceEventId: 'ph-syr-deir-ez-zor-fire',
    primarySource: 'placeholder',
    category: 'fire',
    subcategory: 'fuel_depot_fire',
    severity: 3,
    confidence: 0.79,
    verificationCount: 2,
    title: 'Fuel depot fire near Deir ez-Zor disrupts staging fuel access',
    description: 'Placeholder operational report: a fuel-storage fire near Deir ez-Zor is affecting refuel timing for evacuation support vehicles and increasing heat/smoke exposure around the staging area.',
    tags: ['placeholder', 'syria', 'fire', 'fuel_access'],
    location: { lng: 40.1432, lat: 35.3331 },
    locationName: 'Deir ez-Zor fuel staging edge',
    country: 'Syria',
    reportedAt: hoursAgo(9),
    raw: {
      source: 'placeholder',
      eventType: 'fire',
      eventSubType: 'fuel_depot_fire',
      locationName: 'Deir ez-Zor fuel staging edge',
    },
  },
  {
    sourceEventId: 'ph-irn-tehran-blast',
    primarySource: 'placeholder',
    category: 'explosion',
    subcategory: 'urban_blast',
    severity: 5,
    confidence: 0.9,
    verificationCount: 3,
    title: 'Tehran urban blast creates temporary exclusion zone around transfer hub',
    description: 'Placeholder operational report: a major urban blast near a transfer hub in western Tehran has led to perimeter controls, traffic diversions, and temporary suspension of curbside boarding activity.',
    tags: ['placeholder', 'iran', 'explosion', 'urban_exclusion'],
    location: { lng: 51.389, lat: 35.6892 },
    locationName: 'Western Tehran transfer hub',
    country: 'Iran',
    reportedAt: hoursAgo(2.5),
    raw: {
      source: 'placeholder',
      eventType: 'explosion',
      eventSubType: 'urban_blast',
      locationName: 'Western Tehran transfer hub',
    },
  },
  {
    sourceEventId: 'ph-irn-tabriz-military-activity',
    primarySource: 'placeholder',
    category: 'military_activity',
    subcategory: 'force_mobilization',
    severity: 3,
    confidence: 0.8,
    verificationCount: 2,
    title: 'Tabriz force mobilization increases corridor uncertainty',
    description: 'Placeholder operational report: visible force mobilization around Tabriz is increasing corridor uncertainty and prompting contingency route planning for outbound civilian transport.',
    tags: ['placeholder', 'iran', 'military_activity', 'corridor_uncertainty'],
    location: { lng: 46.2919, lat: 38.0962 },
    locationName: 'Tabriz northern access corridor',
    country: 'Iran',
    reportedAt: hoursAgo(8),
    raw: {
      source: 'placeholder',
      eventType: 'military_activity',
      eventSubType: 'force_mobilization',
      locationName: 'Tabriz northern access corridor',
    },
  },
];

PLACEHOLDER_EVENTS.push(
  {
    sourceEventId: 'ph-ukr-dnipro-rail-yard',
    primarySource: 'placeholder',
    category: 'infrastructure_damage',
    subcategory: 'rail_yard_damage',
    severity: 4,
    confidence: 0.85,
    verificationCount: 2,
    title: 'Dnipro rail yard damage limits high-volume transfer staging',
    description: 'Placeholder operational report: damage across rail-adjacent transfer lanes in Dnipro is reducing throughput for high-volume evacuee transfers and forcing alternate bus marshaling patterns.',
    tags: ['placeholder', 'ukraine', 'rail_damage', 'staging_pressure'],
    location: { lng: 35.0462, lat: 48.4647 },
    locationName: 'Dnipro transfer rail apron',
    country: 'Ukraine',
    reportedAt: hoursAgo(10),
    raw: { source: 'placeholder', eventType: 'infrastructure_damage', eventSubType: 'rail_yard_damage', locationName: 'Dnipro transfer rail apron' },
  },
  {
    sourceEventId: 'ph-ukr-zaporizhzhia-drone-risk',
    primarySource: 'placeholder',
    category: 'airstrike',
    subcategory: 'drone_threat',
    severity: 4,
    confidence: 0.86,
    verificationCount: 2,
    title: 'Zaporizhzhia drone-threat corridor remains unstable for dispatch',
    description: 'Placeholder operational report: continued drone-threat warnings around the Zaporizhzhia outbound corridor are creating recurring release holds for time-sensitive evacuation transport.',
    tags: ['placeholder', 'ukraine', 'drone_threat', 'dispatch_hold'],
    location: { lng: 35.1396, lat: 47.8388 },
    locationName: 'Zaporizhzhia outbound corridor',
    country: 'Ukraine',
    reportedAt: hoursAgo(11),
    raw: { source: 'placeholder', eventType: 'airstrike', eventSubType: 'drone_threat', locationName: 'Zaporizhzhia outbound corridor' },
  },
  {
    sourceEventId: 'ph-lbn-tripoli-port-watch',
    primarySource: 'placeholder',
    category: 'military_activity',
    subcategory: 'coastal_security_mobilization',
    severity: 3,
    confidence: 0.78,
    verificationCount: 2,
    title: 'Tripoli coastal mobilization increases uncertainty at port pickup lanes',
    description: 'Placeholder operational report: visible coastal security mobilization near Tripoli is reducing predictability around port pickup lanes and slowing large-group embarkation sequencing.',
    tags: ['placeholder', 'lebanon', 'coastal_security', 'port_pickup'],
    location: { lng: 35.8497, lat: 34.4367 },
    locationName: 'Tripoli port-adjacent pickup lane',
    country: 'Lebanon',
    reportedAt: hoursAgo(9),
    raw: { source: 'placeholder', eventType: 'military_activity', eventSubType: 'coastal_security_mobilization', locationName: 'Tripoli port-adjacent pickup lane' },
  },
  {
    sourceEventId: 'ph-lbn-sidon-fire-cluster',
    primarySource: 'placeholder',
    category: 'fire',
    subcategory: 'warehouse_fire_cluster',
    severity: 3,
    confidence: 0.8,
    verificationCount: 2,
    title: 'Sidon warehouse fire cluster affects roadside loading visibility',
    description: 'Placeholder operational report: multiple warehouse fires near Sidon are creating smoke and debris conditions that reduce visibility for loading zones and convoy approach lanes.',
    tags: ['placeholder', 'lebanon', 'fire', 'visibility_impact'],
    location: { lng: 35.3715, lat: 33.5631 },
    locationName: 'Sidon warehouse belt',
    country: 'Lebanon',
    reportedAt: hoursAgo(12),
    raw: { source: 'placeholder', eventType: 'fire', eventSubType: 'warehouse_fire_cluster', locationName: 'Sidon warehouse belt' },
  },
  {
    sourceEventId: 'ph-syr-damascus-unrest',
    primarySource: 'placeholder',
    category: 'unrest',
    subcategory: 'checkpoint_crowd_pressure',
    severity: 2,
    confidence: 0.74,
    verificationCount: 2,
    title: 'Damascus checkpoint crowd pressure slows organized civilian transfer',
    description: 'Placeholder operational report: crowd pressure near checkpoint approaches in Damascus is causing repeated compression at handoff points for organized civilian transfer runs.',
    tags: ['placeholder', 'syria', 'unrest', 'checkpoint_pressure'],
    location: { lng: 36.2765, lat: 33.5138 },
    locationName: 'Damascus checkpoint transfer ring',
    country: 'Syria',
    reportedAt: hoursAgo(6),
    raw: { source: 'placeholder', eventType: 'unrest', eventSubType: 'checkpoint_crowd_pressure', locationName: 'Damascus checkpoint transfer ring' },
  },
  {
    sourceEventId: 'ph-syr-latakia-port-block',
    primarySource: 'placeholder',
    category: 'blockade',
    subcategory: 'port_access_restriction',
    severity: 4,
    confidence: 0.82,
    verificationCount: 2,
    title: 'Latakia port-access restriction slows coastal extraction planning',
    description: 'Placeholder operational report: tightened port-access restrictions near Latakia are narrowing heavy-vehicle access windows and slowing coastal extraction planning for staged evacuees.',
    tags: ['placeholder', 'syria', 'blockade', 'port_access'],
    location: { lng: 35.7812, lat: 35.5317 },
    locationName: 'Latakia port access corridor',
    country: 'Syria',
    reportedAt: hoursAgo(13),
    raw: { source: 'placeholder', eventType: 'blockade', eventSubType: 'port_access_restriction', locationName: 'Latakia port access corridor' },
  },
  {
    sourceEventId: 'ph-irn-isfahan-airbase-watch',
    primarySource: 'placeholder',
    category: 'military_activity',
    subcategory: 'airbase_security_surge',
    severity: 3,
    confidence: 0.79,
    verificationCount: 2,
    title: 'Isfahan airbase security surge raises nearby route uncertainty',
    description: 'Placeholder operational report: a security surge around the Isfahan airbase belt is creating uncertain crossing conditions for civilian transfer routes passing nearby.',
    tags: ['placeholder', 'iran', 'military_activity', 'route_uncertainty'],
    location: { lng: 51.6776, lat: 32.6546 },
    locationName: 'Isfahan airbase perimeter corridor',
    country: 'Iran',
    reportedAt: hoursAgo(14),
    raw: { source: 'placeholder', eventType: 'military_activity', eventSubType: 'airbase_security_surge', locationName: 'Isfahan airbase perimeter corridor' },
  },
  {
    sourceEventId: 'ph-irn-bandar-blockade',
    primarySource: 'placeholder',
    category: 'blockade',
    subcategory: 'highway_checkpoint_lockdown',
    severity: 4,
    confidence: 0.84,
    verificationCount: 2,
    title: 'Bandar Abbas highway checkpoint lockdown slows outbound movement',
    description: 'Placeholder operational report: highway checkpoint lockdowns around Bandar Abbas are forcing long stops for outbound buses and reducing schedule reliability for coastal civilian movement.',
    tags: ['placeholder', 'iran', 'blockade', 'highway_lockdown'],
    location: { lng: 56.2666, lat: 27.1832 },
    locationName: 'Bandar Abbas northern highway belt',
    country: 'Iran',
    reportedAt: hoursAgo(15),
    raw: { source: 'placeholder', eventType: 'blockade', eventSubType: 'highway_checkpoint_lockdown', locationName: 'Bandar Abbas northern highway belt' },
  },
  {
    sourceEventId: 'ph-us-indy-downtown-unrest',
    primarySource: 'placeholder',
    category: 'unrest',
    subcategory: 'downtown_crowd_control',
    severity: 2,
    confidence: 0.73,
    verificationCount: 2,
    title: 'Indianapolis downtown crowd-control pressure slows pickup turnover',
    description: 'Placeholder operational report: downtown crowd-control restrictions in Indianapolis are slowing curbside pickup turnover and reducing safe dwell time for evacuation vans.',
    tags: ['placeholder', 'united_states', 'indianapolis', 'unrest'],
    location: { lng: -86.1581, lat: 39.7684 },
    locationName: 'Downtown Indianapolis',
    country: 'United States',
    reportedAt: hoursAgo(5),
    raw: { source: 'placeholder', eventType: 'unrest', eventSubType: 'downtown_crowd_control', locationName: 'Downtown Indianapolis' },
  },
  {
    sourceEventId: 'ph-us-indy-fuel-fire',
    primarySource: 'placeholder',
    category: 'fire',
    subcategory: 'fuel_terminal_fire',
    severity: 3,
    confidence: 0.81,
    verificationCount: 2,
    title: 'Indianapolis east fuel-terminal fire limits dispatch staging',
    description: 'Placeholder operational report: a persistent fuel-terminal fire east of Indianapolis is affecting air quality, staging access, and vehicle refueling schedules for outbound operations.',
    tags: ['placeholder', 'united_states', 'indianapolis', 'fire'],
    location: { lng: -86.0352, lat: 39.7821 },
    locationName: 'East Indianapolis fuel terminal',
    country: 'United States',
    reportedAt: hoursAgo(7),
    raw: { source: 'placeholder', eventType: 'fire', eventSubType: 'fuel_terminal_fire', locationName: 'East Indianapolis fuel terminal' },
  },
  {
    sourceEventId: 'ph-us-indy-checkpoint-blockade',
    primarySource: 'placeholder',
    category: 'blockade',
    subcategory: 'highway_checkpoint',
    severity: 4,
    confidence: 0.84,
    verificationCount: 2,
    title: 'Indianapolis south highway checkpoint creates reroute pressure',
    description: 'Placeholder operational report: a southbound highway checkpoint near Indianapolis is forcing repeated detours, increasing travel time, and complicating dispatch planning for scheduled pickups.',
    tags: ['placeholder', 'united_states', 'indianapolis', 'blockade'],
    location: { lng: -86.1474, lat: 39.7042 },
    locationName: 'South Indianapolis highway approach',
    country: 'United States',
    reportedAt: hoursAgo(4),
    raw: { source: 'placeholder', eventType: 'blockade', eventSubType: 'highway_checkpoint', locationName: 'South Indianapolis highway approach' },
  },
);

function makeRawDocument(event) {
  return {
    source: 'placeholder',
    sourceEventId: event.sourceEventId,
    sourceUrl: `https://placeholder.local/conflict-intel/${event.sourceEventId}`,
    title: event.title,
    description: event.description,
    eventType: event.raw.eventType,
    eventSubType: event.raw.eventSubType,
    lat: event.location.lat,
    lng: event.location.lng,
    locationName: event.locationName,
    country: event.country,
    reportedAt: event.reportedAt,
    fetchedAt: new Date(),
    rawPayload: {
      ...event.raw,
      placeholder: true,
      detailLevel: 'seeded_detailed_placeholder',
      country: event.country,
      coordinates: [event.location.lng, event.location.lat],
    },
    processingStatus: 'processed',
    normalizationError: '',
  };
}

function makeConflictEvent(rawId, event) {
  return {
    eventId: `evt_${event.sourceEventId}`,
    sourceRecords: rawId ? [rawId] : [],
    primarySource: event.primarySource,
    category: event.category,
    subcategory: event.subcategory,
    severity: event.severity,
    confidence: event.confidence,
    verificationCount: event.verificationCount,
    title: event.title,
    description: event.description,
    tags: event.tags,
    location: {
      type: 'Point',
      coordinates: [event.location.lng, event.location.lat],
    },
    locationName: event.locationName,
    country: event.country,
    reportedAt: event.reportedAt,
    expiresAt: computeExpiresAt(event.reportedAt, event.severity),
    status: 'active',
    mergedIntoEventId: '',
    metadata: {
      placeholder: true,
      scenario: 'regional_conflict_demo',
      region: event.country.toLowerCase(),
      seedBatch: '2026-03-29-regional-placeholders',
    },
  };
}

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);

  const expiredAt = new Date();
  await ConflictEvent.updateMany(
    { status: 'active' },
    { $set: { status: 'expired', expiresAt: expiredAt } },
  );

  const rawIds = [];
  for (const event of PLACEHOLDER_EVENTS) {
    const rawDoc = await ConflictRawEvent.findOneAndUpdate(
      { source: 'placeholder', sourceEventId: event.sourceEventId },
      { $set: makeRawDocument(event) },
      { upsert: true, new: true },
    );
    rawIds.push(rawDoc._id);
  }

  for (const [index, event] of PLACEHOLDER_EVENTS.entries()) {
    await ConflictEvent.findOneAndUpdate(
      { eventId: `evt_${event.sourceEventId}` },
      { $set: makeConflictEvent(rawIds[index], event) },
      { upsert: true, new: true },
    );
  }

  const zoneSummary = await buildZones();
  const activeEvents = await ConflictEvent.countDocuments({ status: 'active' });
  const activeZones = await mongoose.connection.collection('conflictzones').countDocuments({
    status: { $in: ['active', 'overridden'] },
    activeUntil: { $gt: new Date() },
  });

  const countries = [...new Set(PLACEHOLDER_EVENTS.map((event) => event.country))];

  console.log(JSON.stringify({
    ok: true,
    seededEvents: PLACEHOLDER_EVENTS.length,
    countries,
    zoneSummary,
    activeEvents,
    activeZones,
  }, null, 2));

  await mongoose.disconnect();
}

seed().catch(async (error) => {
  console.error(JSON.stringify({ ok: false, error: error.message, stack: error.stack }, null, 2));
  try { await mongoose.disconnect(); } catch {}
  process.exit(1);
});
